<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="assets/css/index.css">
</head>
<body>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">

<div>
    <div class="card bg-light register-container">
        <article class="card-body mx-auto" style="max-width: 400px;">
            <h4 class="card-title mt-3 text-center">Create Account</h4>
            <!--<p class="text-center">Get started with your free account</p>-->
            <!--<p>-->
            <!--<a href="" class="btn btn-block btn-twitter"> <i class="fab fa-twitter"></i>   Login via Twitter</a>-->
            <!--<a href="" class="btn btn-block btn-facebook"> <i class="fab fa-facebook-f"></i>   Login via-->
            <!--facebook</a>-->
            <!--</p>-->
            <!--<p class="divider-text">-->
            <!--<span class="bg-light">OR</span>-->
            <!--</p>-->

            <form method="post" action="/accounts/register">
                <?php if (isset($error)) { ?>
                    <div class="alert alert-danger"><?= $error ?></div>
                <?php } ?>
                <div class="form-group input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-user"></i> </span>
                    </div>
                    <input name="name" class="form-control" placeholder="Full name" type="text">
                </div> <!-- form-group// -->

                <div class="form-group input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-envelope"></i> </span>
                    </div>
                    <input name="email" class="form-control" placeholder="Email address" type="email">
                </div> <!-- form-group// -->

                <div class="row no-gutters">
                    <div class="form-group input-group form-phone col">
                        <div class="input-group-prepend">
                            <span class="input-group-text"> <i class="fa fa-phone"></i> </span>
                        </div>
                        <select name="countryCode" class="custom-select m-0 " >
                            <option selected="" value="371">+371</option>
                            <option value="972">+972</option>
                            <option value="198">+198</option>
                            <option value="701">+701</option>
                        </select>
                    </div>
                    <div class="col">
                        <input name="phone" class="form-control" placeholder="Phone number" type="text">
                    </div> <!-- form-group// -->
                </div>

                <div class="form-group input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                    </div>
                    <input name="firstPassword" class="form-control" placeholder="Create password" type="password">
                </div> <!-- form-group// -->

                <div class="form-group input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                    </div>
                    <input name="repeatedPassword" class="form-control" placeholder="Repeat password" type="password">
                </div> <!-- form-group// -->

                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block"> Create Account</button>
                </div> <!-- form-group// -->

                <p class="text-center">Have an account? <a href="./login.html">Log In</a></p>
            </form>
        </article>
    </div> <!-- card.// -->
    <!--container end.//-->
</div>
</body>
</html>